# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1068, 505)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_p = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_p.setGeometry(QtCore.QRect(110, 80, 381, 31))
        self.txt_p.setObjectName("txt_p")
        self.txt_c = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_c.setGeometry(QtCore.QRect(110, 180, 381, 31))
        self.txt_c.setObjectName("txt_c")
        self.txt_i = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_i.setGeometry(QtCore.QRect(680, 80, 381, 31))
        self.txt_i.setObjectName("txt_i")
        self.txt_s = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_s.setGeometry(QtCore.QRect(680, 180, 381, 31))
        self.txt_s.setObjectName("txt_s")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(160, 230, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btndecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btndecrypt.setGeometry(QtCore.QRect(350, 230, 75, 23))
        self.btndecrypt.setObjectName("btndecrypt")
        self.btnsign = QtWidgets.QPushButton(self.centralwidget)
        self.btnsign.setGeometry(QtCore.QRect(720, 230, 75, 23))
        self.btnsign.setObjectName("btnsign")
        self.btn_vify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_vify.setGeometry(QtCore.QRect(930, 230, 75, 23))
        self.btn_vify.setObjectName("btn_vify")
        self.btn_genkeys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_genkeys.setGeometry(QtCore.QRect(640, 30, 75, 23))
        self.btn_genkeys.setObjectName("btn_genkeys")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(560, 90, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(560, 190, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1068, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_encrypt.setText(_translate("MainWindow", "Ecrypt"))
        self.btndecrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btnsign.setText(_translate("MainWindow", "Sign"))
        self.btn_vify.setText(_translate("MainWindow", "Verify"))
        self.btn_genkeys.setText(_translate("MainWindow", "Generatekeys"))
        self.label.setText(_translate("MainWindow", "RSA Cipher"))
        self.label_2.setText(_translate("MainWindow", "Plaintext"))
        self.label_3.setText(_translate("MainWindow", "Ciphertext"))
        self.label_4.setText(_translate("MainWindow", "Information"))
        self.label_5.setText(_translate("MainWindow", "Signature"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
